name: PR Test Checks

on:
  pull_request:
    branches: [ "develop"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu İndir
        uses: actions/checkout@v4

      - name: ☕ Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Kurulumu
        uses: gradle/actions/setup-gradle@v3

      - name: google-services.json Dosyasını Oluştur (Dummy)
        run: |
          echo '{"project_info":{"project_number":"123456789","project_id":"dummy-id"},"client":[{"client_info":{"mobilesdk_app_id":"1:123456789:android:12345","android_client_info":{"package_name":"com.barisproduction.kargo"}},"api_key":[{"current_key":"dummy-key"}]}]}' > composeApp/google-services.json

      - name: Unit Testleri Çalıştır
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest